---
apiVersion: v1
kind: Service
metadata:
  name: user-order-service
  labels:
    app: user-order-service
spec:
  type: NodePort
  selector:
    app: user-order-service
  ports:
  - protocol: TCP
    port: 9090
    name: http
